// ============================================================
// 🔧 PUNTERS CLUB CONFIG - Generated by admin.html 🔧
// ============================================================
// Two pickers per week (sequential pairs through rotation list).
// Each picker submits their own bet.
// ============================================================

const CONFIG = {

  // 📅 Start Date - The Sunday Week 1 began
  startDate: new Date(2026, 1, 15),

  // 💰 Kitty
  kitty: 6315.00,

  // 🎯 This Week's Bets (one per picker)
  bets: [
    {
      description: "No bet placed yet",
      odds: 0
    },
    {
      description: "No bet placed yet",
      odds: 0
    }
  ],

  // Stake per bet
  stake: 50,

  // Member payment status
  members: {
    "Whip": true,
    "Deeks": true,
    "Kingy": true,
    "Pottsy": true,
    "Slug": true,
    "Sauce": true,
    "Pecka": true,
    "Nutty": true,
    "Hutto": true,
    "Baz": true,
    "Pooch": true,
    "Cal": true,
    "Ragsy": true
  },

  // Rotation order (pairs pick each week, wrapping around)
  rotation: ["Whip", "Deeks", "Kingy", "Pottsy", "Slug", "Sauce", "Pecka", "Nutty", "Hutto", "Baz", "Pooch", "Cal", "Ragsy"],

  // Notes
  notes: "$50 per week. Bank details: BSB 923-100 ACC 3013-09085\nFines: BSB 704-230 ACC 1004-75957\n\n\nHoodies status: Label created by sender",

  // 📜 Past Bets History (each week has two bets)
  pastBets: [

  ],

  lastUpdated: "30/04/2026"
};
