// ============================================================
// 🔧 PUNTERS CLUB CONFIG - Generated by admin.html 🔧
// ============================================================

const CONFIG = {

  // 📅 Start Date - The Sunday Week 1 began
  startDate: new Date(2026, 2, 9),

  // 💰 Kitty
  kitty: 100.00,

  // 🎯 This Week's Bet
  bet: {
    description: "No bet placed yet — picker to choose",
    odds: 0
  },

  // Stake per week
  stake: 50,

  // Member payment status
  members: {
    "Whip": false,
    "Deeks": false,
    "Kingy": false,
    "Pottsy": false,
    "Slug": false,
    "Sauce": false,
    "Pecka": false,
    "Nutty": false,
    "Hutto": false,
    "Baz": false,
    "Pooch": false,
    "Cal": false,
    "Ragsy": false
  },

  // Rotation order
  rotation: ["Whip", "Deeks", "Kingy", "Pottsy", "Slug", "Sauce", "Pecka", "Nutty", "Hutto", "Baz", "Pooch", "Cal", "Ragsy"],

  // Notes
  notes: "$50 per week. Bank details: BSB XXX-XXX ACC XXXXXXXX",

  // 📜 Past Bets History
  pastBets: [

  ],

  lastUpdated: ""
};
