// ============================================================
// 🔧 PUNTERS CLUB CONFIG - Generated by admin.html 🔧
// ============================================================
// Two pickers per week (sequential pairs through rotation list).
// Each picker submits their own bet.
// ============================================================

const CONFIG = {

  // 📅 Start Date - The Sunday Week 1 began
  startDate: new Date(2026, 1, 15),

  // 💰 Kitty
  kitty: 0.00,

  // 🎯 This Week's Bets (one per picker)
  bets: [
    {
      description: "No bet placed yet",
      odds: 0
    },
    {
      description: "No bet placed yet",
      odds: 0
    }
  ],

  // Stake per bet
  stake: 50,

  // Member payment status
  members: {
    "Whip": false,
    "Deeks": false,
    "Kingy": false,
    "Pottsy": false,
    "Slug": false,
    "Sauce": false,
    "Pecka": false,
    "Nutty": false,
    "Hutto": false,
    "Baz": false,
    "Pooch": false,
    "Cal": false,
    "Ragsy": false
  },

  // Rotation order (pairs pick each week, wrapping around)
  rotation: ["Whip", "Deeks", "Kingy", "Pottsy", "Slug", "Sauce", "Pecka", "Nutty", "Hutto", "Baz", "Pooch", "Cal", "Ragsy"],

  // Notes
  notes: "$50 per week. Bank details: BSB XXX-XXX ACC XXXXXXXX",

  // 📜 Past Bets History (each week has two bets)
  pastBets: [

  ],

  lastUpdated: ""
};
